language: php

php:
  - 7.3
  - 7.2
  - 7.1

git:
  depth: 3

install:
  - make /usr/local/bin/phive cc-test-reporter
  - phive install --trust-gpg-keys 4AA394086372C20A,8E730BA25823D8B5,2420BAE0A3BE25C6
  - phive status
  - bin/phing setup

before_script:
  - bin/phing code-climate:before

script:
  - bin/phing test

after_script:
  - bin/phing code-climate:after
