language: php
php:
  - '7.1'

git:
  depth: 3

install:
  - make cc-test-reporter
  - make phing.phar
  - ./phing.phar setup

before_script:
  - ./phing.phar code-climate:before

script:
  - ./phing.phar test

after_script:
  - ./phing.phar code-climate:after
