default:
  suites:
    class_features:
      paths:
      - '%paths.base%/../tests/behat/class/'
      contexts:
      - \Jawira\PhingVisualizer\Behat\ClassContext
    executable_features:
      paths:
      - '%paths.base%/../tests/behat/executable/'
      contexts:
      - \Jawira\PhingVisualizer\Behat\ExecutableContext
  formatters:
    pretty: true
